name: Update online Doxygen documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_online_documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: gh-pages
          folder: doc/html
